---
- name: Copy a single file to Windows, and keep a backup
  hosts: windows_servers
  tasks:
    - name: Copy the JDK installer to the remote Windows server
      win_copy:
        src: /ansible/projects/java/update/jdk-8u411-windows-x64.exe
        dest: C:\temp\jdk-8u411-windows-x64.exe
        backup: true


