---
- name: Copy a single file, but keep a backup.
  hosts: windows_servers
  ansible.windows.win_copy:
    src: /ansible/projects/java/update/jdk-8u411-windows-x64.exe
    dest: C:\temp\jdk-8u411-windows-x64.exe
    backup: true


