---
- name: Install Java on Windows
  hosts: all
  gather_facts: no
  tasks:
    - name: Copy JDK Installer
      win_copy:
        src: "/home/ec2-user/jdk-17_windows-x64_bin.exe"
        dest: "C:\\Users\\bpmdcuser\\Downloads\\jdk-17_windows-x64_bin.exe"

    - name: Install Java
      win_package:
        path: "C:\\Users\\bpmdcuser\\Downloads\\jdk-17_windows-x64_bin.exe"
        arguments: "/s"
        state: present

    - name: Set JAVA_HOME Environment Variable
      win_environment:
        name: JAVA_HOME
        value: "C:\\Program Files\\Java\\jdk-17"
        state: present
        level: machine
