---
- name: Install JDK on Windows
  hosts: windows-hosts
  tasks:
    - name: Copy JDK installer to Windows Hosts
      win_copy:
        src: "/home/ec2-user/jdk-17_windows-x64_bin.exe"
        dest: "C:\\Users\\Administrator\\Downloads\\jdk-17_windows-x64_bin.exe"

    - name: Install JDK
      win_shell: |
        C:\Users\Administrator\Downloads\jdk-17_windows-x64_bin.exe /s

    - name: Set JAVA_HOME environment variable
      win_environment:
        name: JAVA_HOME
        value: "C:\\Program Files\\Java\\jdk-17"
        state: present
        level: machine

    - name: Add Java to System Path
      win_path:
        elements:
          - "C:\\Program Files\\Java\\jdk-17\\bin"
